### ISSUE TITLE
Fine tuning model using Bhashini transliterate 

### ISSUE THREAD

**Issue by Gautam-Rajeev** [DataGov-SamagraX/Bhashini_exploration#2]
Using provided data (sample of Bhulekh plot tenant names in Odiya)  to fine tuning existing Bhashini existing transliterate model.

**Comment by GautamR-Samagra** [comment]
Use data available of plot tenant names to fine tune Bhashini transliterate models

**Comment by Gautam-Rajeev** [comment]
Estimated time:  2 days

**Comment by Gautam-Rajeev** [comment]
Closed incorrectly
